# Dockerfile.frontend
FROM python:3.10-slim

WORKDIR /app

# Copy frontend code
COPY frontend/ /app

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Ensure script is executable
RUN chmod +x start-frontend.sh

# Run Streamlit
CMD ["./start-frontend.sh"]
