services:
  - type: web
    name: rag-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: PORT
        value: 8000

  - type: web
    name: rag-frontend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run frontend/app.py --server.port=8501 --server.address=0.0.0.0
    envVars:
      - key: PORT
        value: 8501
      - key: API_URL
        value: https://rag-backend.onrender.com  # 🔗 Replace with your actual backend URL after first deploy
